### PR TITLE
Added support for learn.microsoft.com

### PR DESCRIPTION
**Pull request by LinnZawWin**
docs.microsoft.com has been changed to learn.microsoft.com

### CODE REVIEW

**Comment by mjisaak** [comment]
Hi @LinnZawWin,

Thank you for your contribution 👋. I have written Microsoft asking if learn.microsoft.com is tracked by the Skilling Champion program. I expect and hope that this is the case. If so, I will be happy to accept your pull request and release the version to the marketplaces. 

Best regards,
Martin

**Comment by flcdrg** [comment]
I've just been chatting with Shiva Ford from Microsoft about this and she confirmed that 'learn.microsoft.com' should be included.

**Review by flcdrg — APPROVED** [review]

**Comment by LinnZawWin** [comment]
Awesome... Thanks.

**Comment by flcdrg** [comment]
@LinnZawWin why did you close this? Don't you want to allow it to be merged?

**Comment by LinnZawWin** [comment]
@flcdrg My bad. I pressed the wrong button "Close with comment" instead of the "Comment" button. 😅

**Comment by mjisaak** [comment]
I created a new release v1.4.6 containing your changes and uploaded it to the marketplaces.

**Pull request merged**
