### PR TITLE
Add support for code.visualstudio.com

### PR DESCRIPTION
**Pull request by Balastrong**
Hey! I think this is included too :)

### CODE REVIEW

**Comment by mjisaak** [comment]
Hi Leonardo,

thank you very much for your support. 
Are you sure this site is part of the Skilling Champion program? Where did you get this information? 
If you can confirm that the site is part of the program, I will gladly take over the PR.

**Comment by Balastrong** [comment]
Hey, it's in [this sway page](https://sway.cloud.microsoft/y861j7eZsxZoa9Xh) (I assume it's not under NDA)

**Comment by mjisaak** [comment]
You are right, I was not aware of this page. Thank you!

**Comment by mjisaak** [comment]
@Balastrong - Your contribution (support for code.visualstudio.com) will be part of version 1.5.1. I have just uploaded it to the Chrome and Edge store and waiting for an approval. Should be available within the next few days.
BR

**Pull request merged**
