### PR TITLE
Update main.js

### PR DESCRIPTION
**Pull request by MikeCarlo**
Add links to Power BI, Fabric and Community sites for Fabric and Power BI.

I would like to include these other sites for Power BI and Fabric related blog and community sites. I am often on these sites and would like to include my MVP ID for these as well.

### CODE REVIEW

**Comment by MikeCarlo** [comment]
No problem I ask also asked the question to Rei Merrit to see if these pages are also tracked.  Waiting on a response also.

Mike Carlo
PowerBI.Tips
***@***.***
________________________________

**Comment by mjisaak** [comment]
@MikeCarlo, Have you received any feedback? I am still waiting for an answer from the skillingchampion support team.

**Comment by AnthonyByansi** [comment]
Hi @mjisaak 
From the feedback I got from the student ambassador technical team, it looks the sites aren't supported as of yet

**Comment by mjisaak** [comment]
> Hi @mjisaak From the feedback I got from the student ambassador technical team, it looks the sites aren't supported as of yet

Hi @AnthonyByansi!
Thank you very much for the feedback. Then I will wait a few more days for a response from the skillingchampion team and probably close this PR because the site is not supported. 

BR,
Martin

**Comment by AnthonyByansi** [comment]
@mjisaak & @MikeCarlo Updates from the Student Ambassador Technical Support team indicate that the `fabric.community.microsoft.com` site is now receiving support for skilling Champion Program.

Communications from Tracey Salem—Senior program Manager

**Review by mjisaak — APPROVED** [review]

**Comment by mjisaak** [comment]
@AnthonyByansi Thanks for the update. I will approve the PR and start rolling out the new version to the Marketplaces, even "powerbi.microsoft.com" is not yet confirmed. 
BR Martin

**Pull request merged**
