### PR TITLE
Add option to include text in link

### PR DESCRIPTION
**Pull request by flcdrg**
Adds an option that when true, prepends text that is linked before the link URL

- Also, don't allow adding an empty creator id.

### CODE REVIEW

**Comment by mjisaak** [comment]
Hi David! 
Thanks for the PR. I tried to load and test the updated extension locally. When I enable the "include text with link" option, I always get **undefined** as the link text:

```
undefined
https://docs.microsoft.com/en-us/aspnet/core/getting-started/?view=aspnetcore-5.0&WT.mc_id=AZ-5003203
```

I can try to investigate on the weekend if you are busy :-). BR

**Comment by flcdrg** [comment]
oh.. that's not good! 

I'll see if I can do some more testing myself. Good thing you checked it.

**Comment by flcdrg** [comment]
Looks like only Firefox currently supports the linkText property that I'm depending on.

**Comment by mjisaak** [comment]
I can confirm that I don't get any information about the link text in chrome:
image

I suggest closing this PR for now until chrome provides us the option to retrieve the link text

**Pull request closed without merging**
